require "./models"

User.create(username: "orlandoc", password: "123",firstName:"Orlando",lastName:"Caraballo", email:"orlando@nycda.com", birthday:Time.now)
User.create(username: "minhalg", password: "123", firstName:"Minhal",lastName:"Gardezi",email:"mag166@case.edu", birthday:Time.now)
User.create(username: "martin", password: "123", firstName:"Sir",lastName:"Martin",email:"minhaldabest@martin.edu", birthday:Time.now)


Post.create(title:"Arsenal must clear the rubble of Arsene Wenger's fallen empire", content:"Cold reality is now staring Arsenal in the face. The Wenger era has three games left to run -- Burnley at home, Leicester away and then the long goodbye at Huddersfield -- and the future must now be about the rebuilding job that lies ahead for the club and whomever they appoint to clear the rubble of Wenger's fallen empire.",img_link:"https://www.ghanacrusader.com/wp-content/uploads/2018/04/wenger-out-arsene-wenger-1.jpg", user_id:1)
Post.create(title:"Falcao is a crappy striker", content:"No news here. Falcao is so poop nobody should ever sign him.", img_link:"http://i.dailymail.co.uk/i/pix/2015/01/12/2499863B00000578-2907273-image-m-7_1421098835338.jpg", user_id:2)
Post.create(title:"Barcelona and Real Madrid serve up Clasico full of fire and fury", content:"The first thing to ask is not which side should actually have won a bad-tempered, chance-filled Clasico that actually ended 2-2, or how the heck referee Alejandro Jose Hernandez Hernandez managed to have such a bad game? No, anyone who appreciates football played like this, at full-tilt and constantly simmering with the cordite of something explosive, should wonder how on earth do these players keep doing it", img_link:"https://3.bp.blogspot.com/-lgwMlro1828/Wj2VDRG5K3I/AAAAAAAAAdg/x2LYzgdqWbo9buX0XS7bc8FWNVMzsDCJgCLcBGAs/s1600/El%2Bclassico.png",user_id:3)
Post.create(title:"Antonio Conte the anti-Jurgen Klopp as coaching styles collide at Stamford Bridge", content:"There was a time when Liverpool and Chelsea were happy to see themselves as opposites. Rewind to a rivalry that developed rapidly and vitriolically when Rafa Benitez and Jose Mourinho took charge of the two clubs. Traditional force vs. nouveaux riches, northerners vs. southerners, Champions League winners vs. Premier League champions, the two liked to prove they were the antithesis of the other.", user_id:2)
Post.create(title:"Wayne Rooney lost at Everton", content:"As Everton prepare for their final home game of the season, the visit of relegation-threatened Southampton on Saturday, attention will soon turn to next season. For eight players, their first campaign at the club is drawing to a close. Some might not last much longer at Everton.", img_link:"http://e1.365dm.com/17/07/16-9/20/skysports-wayne-rooney-everton-football_4005799.jpg?20170720095152", user_id:2)
Post.create(title:"Manchester United is the best team", content:"The best team ever. So Good. Unstoppable. What you gonna do when they come for you.", user_id:1)
Post.create(title:"Minhal Gardezi signs for Manchester United", content:"The summer transfer everyone has been waiting for has arrived. Minhal Gardezi was signed from NYCDA FC for a record $250 million. As the greatest player to ever play the game it was a bargain. Excpect to see great things from him this coming season", img_link:"https://image.ibb.co/ctKbtn/IMG_3602.jpg",user_id:1)
Post.create(title:"Real's unpredictability make them impossible to prepare for", content:"Something happened on Sunday night at the Camp Nou that should truly scare Liverpool. It wasn't the fact that their Champions League final opponents stood toe-to-toe with Barcelona in such a fashion or the haranguing of the referee that influenced proceedings. In fact, this particular something has been happening for the last couple of months. It has been propelled by injuries and inconsistency and helped by Zinedine Zidane's inventiveness. But the fact is, Real Madrid have no team or template for opponents to plan against. They are becoming increasingly difficult to play because they can defend against you depending on how you attack and attack against you depending on how you plan to defend them. There is no dogma when it comes to how Real Madrid see football and they can beat you whatever way it takes", img_link:"http://a.espncdn.com/combiner/i?img=%2Fphoto%2F2018%2F0426%2Fr361785_1296x729_16%2D9.jpg&w=1140&cquality=40", user_id:1)
Post.create(title:"Chelsea have hope in top-four race", content:"If Spurs were too far ahead to catch, then Liverpool, in third, were as good as over the horizon with their 10-point lead over Chelsea seemingly enough to banish any prospect of them slipping out of the top four during the final weeks of the season. But after Olivier Giroud's first-half header delivered a 1-0 win against Liverpool at Stamford Bridge, the scramble for fourth during this final week of the campaign was triggered, with Conte admitting that he thought a top-four finish was impossible after the Spurs defeat.", img_link:"http://a4.espncdn.com/combiner/i?img=%2Fphoto%2F2018%2F0506%2Fr366618_1296x729_16%2D9.jpg&w=1140&cquality=40", user_id:3)